[build]
publish = "." # 指定部署时发布的目录为当前根目录 "."
# 定义需要忽略的文件和文件夹
ignore = [
    ".venv",        # Python 虚拟环境文件夹
    ".vscode",      # VSCode 配置文件夹
    "app",
    "static",
    "README.md",
    "netlify.toml",
]
